name: Automated deploy

on:
  release:
    types: [created]

env:
  VERSION: ${{ github.event.release.tag_name }}
  TAG: ${{ github.event.release.target_commitish == 'master' && 'latest' || 'next' }}

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
          token: ${{ secrets.GPR_TOKEN }}

      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'

      - name: Cache npm modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ inputs.cache }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ inputs.cache }}-

      - name: Install deps in quiet mode
        run: npm ci -q

  build:
    runs-on: ubuntu-latest
    needs: install-deps
    env:
      VERSION: ${{ github.event.release.tag_name }}
      TAG: ${{ github.event.release.target_commitish }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
          token: ${{ secrets.GPR_TOKEN }}

      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'

      - name: Cache npm modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ inputs.cache }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ inputs.cache }}-

      - name: Install deps in quiet mode
        run: npm ci -q

      - name: Build package
        run: npm run build

      - name: Set package version
        run: npm version --no-git-tag-version $VERSION

      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            dist
            package.json
            package-lock.json
            README.md
            LICENSE

  publish-to-npm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build

      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'

      - name: Cache npm modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ inputs.cache }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ inputs.cache }}-

      - name: Install deps in quiet mode
        run: npm ci -q

      - name: Publish package to NPM
        run: npm publish --tag $TAG
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-to-gpr:
    runs-on: ubuntu-latest
    needs: build
    env:
      VERSION: ${{ github.event.release.tag_name }}
      TAG: ${{ github.event.release.target_commitish }}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build

      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://npm.pkg.github.com'
          scope: '@NeuraLegion'

      - name: Cache npm modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ inputs.cache }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ inputs.cache }}-

      - name: Install deps in quiet mode
        run: npm ci -q

      - name: Publish package to GPR
        run: npm publish --tag $TAG
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_TOKEN }}
